apiVersion: v1
kind: ConfigMap
metadata:
  name: archiver-config
data:
  archiver.conf: |
    saps_execution_period_archiver=300
    saps_execution_period_garbage_collector=30
    saps_debug_mode=true
    saps_permanent_storage_type=swift
    datastore_ip=saps-catalog.default.svc.cluster.local
    datastore_port=5432
    datastore_name=saps
    datastore_driver=org.postgresql.Driver
    datastore_username=admin
    datastore_password=admin
    saps_temp_storage_path=/archiver/nfs
    permanent_storage_debug_tasks_dir=trash
    permanent_storage_tasks_dir=archiver
    openstack_object_store_service_container_name=saps
    openstack_project_id=<project_id>
    openstack_user_id=<user_id>
    openstack_user_password=<pass>
    openstack_identity_service_api_url=<endpoint_url>
    openstack_object_store_service_api_url=<objectstore_url>
    openstack_object_store_service_key=1a2b3c4d
  log4j.properties: |
    log4j.rootLogger=DEBUG, file, stdout
    log4j.category.org.restlet=INFO
    log4j.category.org.apache.http=INFO
    log4j.appender.DatePattern='.'yyyy-MM-dd
    log4j.appender.file=org.apache.log4j.DailyRollingFileAppender
    log4j.appender.file.File=/var/tmp/saps-engine/logs/log4j.log
    log4j.appender.file.layout=org.apache.log4j.PatternLayout
    log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-saps-archiver
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      name: "nfs"
  storageClassName: nfs
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: saps-archiver
  labels:
    app: saps-archiver
spec:
  containers:
  - name: archiver
    image: ufcgsaps/archiver
    volumeMounts:
    - name: archiverconf-volume
      mountPath: /archiver
    - name: nfs-archiver
      mountPath: "/archiver/nfs"
  volumes:
  - name: archiverconf-volume
    configMap: 
      name: archiver-config
  - name: nfs-archiver
    persistentVolumeClaim:
      claimName: nfs-saps-archiver